version: '2'

services:
    db:
        image: mariadb:latest
        volumes:
            - "../data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: wiseflow
            MYSQL_USER: wiseflow
            MYSQL_PASSWORD: test
        networks:
            - site
        ports:
            - 3306:3306
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: test
        networks:
            - site
    php:
        build: php-fpm
        image: test-php:latest
        networks:
            - site
        environment:
            SERVER_ENVIRONMENT: "local"
            DATABASE_URL: "mysql://wiseflow:test@db/wiseflow"
        volumes:
            - ./app:/app/
            - ../cache:/var/cache/symfony
    nginx:
        depends_on:
            - php
        build:
            context: .
            dockerfile: nginx/Dockerfile
        image: test-nginx:latest
        ports:
            - 80:80
        networks:
            - site

networks:
    site:
        driver: bridge